<?php 
$_order = $block->getOrder();
echo "Order Id : " . $_order->getIncrementId();
$orderItems = $block->getOrderData($_order->getId());
?>
<?php foreach($orderItems as $item):

?>
	<table cellpadding="0" cellspacing="0" width="100%" style="border: 1px solid #e6e6e6;">
		<?php if($item['feedback_rating'] == ""):?>
			<tr>
				<td width="33.3333%" style="font-size: 14px; color: #000; padding: 10px;">
					<span style="padding-top: 20px; display: block;">
						<?php echo $item['product_name'];?>
					</span>
				</td>
				<td width="33.3333%" style="text-align: center; padding: 10px;">
					<img src="<?php echo $item['product_image'];?>" style="width: 50px; height: 50px; padding: 5px; border: 1px solid #d1d1d1; background-color: #fff;">
				</td>
				<td width="33.3333%" style="font-size: 14px; color: #000; padding: 10px;">
					<span style="padding-top: 20px; display: block;">
					<a style="color: #000; font-size: 14px;" href="<?php echo $this->getBaseUrl().'customer/account';?>">
						<?php //echo __('Give Feedback on this item')?>
						<img src="<?php echo $block->getViewFileUrl('Krishaweb_Feedback::images/star.png')?>" style="width: 100px; display: inline-block;">
					</a>
					</span>
				</td>
			</tr>
		<?php endif;?>
	</table>
<?php endforeach;?>